version: '3.7'

services:
  minio:
    image: minio/minio:latest
    restart: unless-stopped
    command: server /data
    environment:
      - MINIO_ACCESS_KEY
      - MINIO_SECRET_KEY
    volumes:
      - minio-vol:/data

volumes:
  minio-vol:
